[package]
name = "griddle"
version = "0.1.0"
authors = ["Contributors to Hyperledger Grid"]
edition = "2018"
license = "Apache-2.0"
description = "Grid integration component"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
clap = "2.33.3"
diesel = { version = "1.0", features = ["r2d2"] }
flexi_logger = "0.14"
grid-sdk = { path = "../sdk", features = ["rest-api-actix-web-3"] }
log = "0.4"
users = "0.11"
